# arxivの学問領域の指定
subject: 'cat:cs.AI'

# 検索キーワード
keywords:
        transformer: 3
        attention: 3
        kaggle: 3
        anomaly detection: 3
        GPT: 3
        GAN: 3
        VAE: 3
        

# 通知の閾値
score_threshold: 0
